#!/bin/sh

# Set LAN IP to 192.168.1.9
uci set network.lan.ipaddr='192.168.1.9'
uci set network.lan.proto='static'
uci set network.lan.netmask='255.255.255.0'

# Disable DHCP
uci set dhcp.lan.ignore='1'

# Disable IPv6
uci set network.lan.ipv6='0'
uci set dhcp.lan.dhcpv6='disabled'
uci set dhcp.lan.ra='disabled'

# Configure gateway and DNS to main router
uci set network.lan.gateway='192.168.1.8'
uci set network.lan.dns='192.168.1.8'

# Disable firewall rules (let main router handle)
uci set firewall.@defaults[0].input='ACCEPT'
uci set firewall.@defaults[0].output='ACCEPT'
uci set firewall.@defaults[0].forward='ACCEPT'
uci set firewall.@defaults[0].synflood_protect='0'

# Enable IP forwarding for transparent proxy
uci set firewall.@defaults[0].flow_offloading='0'

# Save changes
uci commit network
uci commit dhcp
uci commit firewall

# Enable IP forwarding
echo 1 > /proc/sys/net/ipv4/ip_forward

# Restart services
/etc/init.d/network restart
/etc/init.d/dnsmasq restart
/etc/init.d/firewall restart

exit 0
