#!/bin/sh

# Set default language to Chinese
uci set luci.main.lang='zh_cn'
uci commit luci

# Configure ttyd for Web SSH
uci set ttyd.@ttyd[0].interface='@lan'
uci set ttyd.@ttyd[0].port='7681'
uci set ttyd.@ttyd[0].command='/bin/login'
uci commit ttyd

# Enable services on boot
/etc/init.d/ttyd enable
/etc/init.d/momo enable

# Start services
/etc/init.d/ttyd start

# Configure momo to use pre-installed sing-box
if [ -f /usr/bin/sing-box ]; then
    # Create symlink if needed
    ln -sf /usr/bin/sing-box /usr/bin/sing-box-core
    
    # Start momo service
    /etc/init.d/momo start
fi

exit 0
