#!/bin/sh

# 旁路由网络配置 - IP: 192.168.1.9, Gateway: 192.168.1.8

# 设置LAN IP
uci set network.lan.ipaddr='192.168.1.9'
uci set network.lan.proto='static'
uci set network.lan.netmask='255.255.255.0'
uci set network.lan.gateway='192.168.1.8'
uci set network.lan.dns='192.168.1.8'

# 禁用IPv6
uci set network.lan.ipv6='0'
uci delete network.lan.ip6assign 2>/dev/null || true

# 禁用DHCP
uci set dhcp.lan.ignore='1'
uci set dhcp.lan.dhcpv6='disabled'
uci set dhcp.lan.ra='disabled'

# 防火墙透传模式
uci set firewall.@defaults[0].input='ACCEPT'
uci set firewall.@defaults[0].output='ACCEPT'
uci set firewall.@defaults[0].forward='ACCEPT'
uci set firewall.@defaults[0].synflood_protect='0'

# 保存
uci commit network
uci commit dhcp
uci commit firewall

# 启用IP转发
echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.conf

exit 0
